/**
 * Minimal typed surface of the untyped `web-push` CJS package (v3.x), limited to what PI WEB uses.
 *
 * Declared with `export =` on purpose: the package's index.js builds its exports object with a
 * `.bind()` expression, which Node's cjs-module-lexer cannot detect as named exports — only the
 * default import is reliable at ESM runtime (vitest's own interop masks this, so keep using the
 * default import form here).
 */
declare module "web-push" {
  /** VAPID identity for one send; the subject is the RFC 8292 contact claim. */
  export interface WebPushVapidDetails {
    /** "mailto:…" or https URL, validated by web-push. */
    readonly subject: string;
    /** Base64url public key (as generated by `web-push generate-vapid-keys`). */
    readonly publicKey: string;
    /** Base64url private key from the same key pair. */
    readonly privateKey: string;
  }

  interface WebPushSendOptions {
    /** Per-send VAPID identity, used instead of any process-global `setVapidDetails` state. */
    vapidDetails?: WebPushVapidDetails;
  }

  interface WebPushModule {
    /** Push-service HTTP failures reject with an error carrying `statusCode` (404/410 = expired endpoint). */
    sendNotification(
      subscription: { endpoint: string; expirationTime?: number | null; keys: Readonly<Record<string, string>> },
      payload: string,
      options?: WebPushSendOptions,
    ): Promise<{ statusCode?: number | undefined }>;
  }

  const webPush: WebPushModule;
  export = webPush;
}
